### ISSUE TITLE
Accommodating missing data in line chart

### ISSUE THREAD

**Issue by grgcombs** [honcheng/iOSPlot#1]
I really like your new charting library.  Very lightweight, visually appealing.

I have a request relating to chart lines that permit "missing" data.  For example, if your chart shows yearly sales figures for your sales associates, and one of those associates left the company at the beginning of 2008, but returned in 2009, you wouldn't want his figures to appear as 0.00 sales for 2008.  Rather he should have a broken line between 2007 and 2009.

In terms of the data points array, a missing data point could be represented by NSNull or something...

**Comment by honcheng** [comment]
This is done. 

Plist does not support null values, so I have to add JSON support for a list to include null values. You need to update the submodule to get the JSON code

**Comment by grgcombs** [comment]
Awesome, thanks!
