### ISSUE TITLE
JSONKit not included?

### ISSUE THREAD

**Issue by adamgit** [honcheng/iOSPlot#11]
github doesn't support gitmodules well, I suggest embedding JSONKit directly, or adding a note to the readme saying which exact version you're using.

(if you hit the download link on github main page, it either fails or doesn't even try to download JSONKit)

**Comment by honcheng** [comment]
you can just run

git submodule init
git submodule update

after you clone the project, and it will pull the submodules for you.

On Sat, Mar 3, 2012 at 11:44 PM, adamgit <
reply@reply.github.com
