### ISSUE TITLE
Build fails with duplicate symbol error

### ISSUE THREAD

**Issue by adamgit** [honcheng/iOSPlot#12]
ld: duplicate symbol _jk_collectionClassLoadTimeInitialization in Xcode/DerivedData/PlotCreator-ccpudyikljtxvkfwhdgepyofgolj/Build/Intermediates/PlotCreator.build/Debug-iphonesimulator/PlotCreator.build/Objects-normal/i386/JSONKit-E0F2220995BD635C.o and Xcode/DerivedData/PlotCreator-ccpudyikljtxvkfwhdgepyofgolj/Build/Intermediates/PlotCreator.build/Debug-iphonesimulator/PlotCreator.build/Objects-normal/i386/JSONKit-E0F2220995BD635C.o for architecture i386
Command /Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/clang failed with exit code 1

**Comment by honcheng** [comment]
did you already have JSONKit in your existing project? Looks like you
import it twice.

On Sat, Mar 3, 2012 at 11:54 PM, adamgit <
reply@reply.github.com
