### ISSUE TITLE
Crash in LineChart

### ISSUE THREAD

**Issue by acidjunk** [honcheng/iOSPlot#28]
Hi,

compile went OK after installing JSONKit from github.

JSONKit.h and JSONKit.m where missing...
(I don't know if that's the correct way?)

The Pie charts and the Half Pie chart work as expected. 

Line chart crashes the app.
When starting line chart, it logs:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString objectFromJSONString]: unrecognized selector sent to instance

Kind Regards,
Rene

**Comment by hungntv** [comment]
Hi
Click on red zone, you will see how it work. Or check out by xcode with Git link (not svn link)
![screen shot 2013-07-31 at 10 44 04 am](https://f.cloud.github.com/assets/4994141/883761/b605c9b8-f993-11e2-94d7-732450eb6ca2.png)

**Comment by acidjunk** [comment]
Hi,

I did a normal git clone e.g.: git clone https://github.com/honcheng/iOSPlot.git iOSPlot2 and also tried it the graphical way from inside xCode.

both attempts have an empty JSON folder. So i figured i needed branch 82157634ca from JSONKit:
cd JSONKit
git clone https://github.com/johnezang/JSONKit.git .
git checkout 82157634ca

And indeed: linecharts are working now. Thanks for the info. (I didn't use the webGUI from github..)

Rene
